%YAML:1.0

#------------------------------------------------- Hav Map param ------------------------------------------------

layer_limit: 4
root_surf_voxel_size: 1
window_size: 9                 # BA 的关键帧数量等于 window_size + fix_size
fix_size: 1                     

#--------------------------------------------------- BA param ---------------------------------------------------

opt_type: 1                       # 1=balm2, 2=pa(ceres)
opt_iterations: 20                # 外部迭代次数 20, 10, 20, 20

#------------------------------------------- preprocess down sampling param -------------------------------------

ds_size: 0.1
