%YAML:1.0

#------------------------------------------------- Hav Map param ------------------------------------------------

layer_limit: 3
root_surf_voxel_size: 2
window_size: 9                   # BA 的关键帧数量等于 window_size + fix_size
fix_size: 1        
           
#--------------------------------------------------- BA param ---------------------------------------------------

opt_type: 1                       # 0=r2s-pa, 1=balm2, 2=pa(ceres), 3=1+0(fusion method)
opt_iterations: 20                # 外部迭代次数

#----------------------------------------- preprocess down sampling param ---------------------------------------

ds_size: 0.2
